export default {
    az: {
        "reset_password": "Parolu sıfırlamak",
        'send_reset_p_link': "Şifrə sıfırlama bağlantısını göndərin",
        'sending':"göndərir",
        'name': "Ad",
        'phone_number': 'Telefon nömrəsi',
        'confirm_password': "Şifrəni təsdiq edin",
        'bterm_conditions': "Qeydiyyatdan keçərək Qaydalar və Şərtlərimizi qəbul edirsiniz",
        'or_sign_up_with': "və ya ilə qeydiyyatdan keçin",
        'already_account': 'Artıq bir hesabınız var mı',
        'create_account': 'Hesab yarat',
        "conditions": 'Şərtlər',
        "term": "müddət",
        "privacy": "Məxfilik",
        "policy": " Siyasət",
        "and": "Və",
        "method": "Metod",
        "_faqs": "Suallar",
        "delivery": "Çatdırılma",
        "options": "Seçimlər",
        "buyer": "Alıcı",
        "_protection": "Qoruma",
        "affiliate": "Tərəfdaş",
        "program": "Proqram",
        'brands': 'Markalar',
        'types': 'növləri',
        'colors': 'Rənglər',
        'sizes': "Ölçülər",
        'category_name': 'Kateqoriya Adı',
        'filter': 'filtr',
        'shippings': "Daşınmalar",
        'minimum_price': "Minimum qiymət",
        'maximum_price': "Maksimum qiymət",
        'price_icon': "₼",
        "recently_rev_notfications": "Bu yaxınlarda alınan bildirişlər",
        "unfollow": "İzləməyin",
        'go_to_homepage': "Ana səhifəyə keçin",
        'login_feel_mystore_desc': "Giriş yapın və Mystore'da əməliyyatların asanlığını hiss edin",
        'buy_sell_mystore_desc': "Yalnız Mystore'da asanlıqla al və sat",
        'register_now': 'İndi qeydiyyatdan keç',
        'need_an_account': "Bir hesaba ehtiyac var",
        'or_login_with': "və ya ilə daxil olun",
        'checking': "yoxlama",
        'forgot_passowrd': 'Şifrəni unutmusunuz',
        'remember_me': "Məni xatırla",
        'password': 'Şifrə',
        'email': "Elektron poçt",
        'login_header': 'Giriş Başlığı',
        "currenci": "Valyuta",
        "language": "Dil",
        "store_location": "Mağaza yeri",
        "review_message": "Yalnız qeydiyyatdan keçmiş istifadəçilər rəy yaza bilərlər",
        'submitreview': "Rəy göndərin",
        "open": "Açıq",
        "closed": "Bağlı",
        "exp_holidays": "Tətil günləri istisna olmaqla",
        "operating_hours": "İş saatları",
        "store_information": "Mağaza haqqında məlumat",
        "shopping": "Alış-veriş",
        "following": "İzləyirəm",
        "chat": "Çat",
        "nFlashpf": "Heç bir flaş razılaşma məhsulu tapılmadı",
        "flash_deal_products": "Flash Deal Məhsulları",
        "your_msg": "Sənin mesajın",
        "select_subject": "Mövzu seçin",
        "general_enquiry": "Ümumi sorğu",
        "feedback_ois": "Sayılar / Hata haqqında Əlaqə",
        "adver_enq": "Reklam sorğusu",
        "send_msg": "Mesaj göndər",
        "your_name": "Adınız*",
        "your_email": "E-poçtunuz*",
        "your_phone": "Sənin telefonun*",
        "contact_description": "Hesabınızla bağlı bir sualınız və ya bir probleminiz var? Narahat olmayın, bizə bildirin və günün istənilən vaxtında sizinlə görüşəcəyik! Məhsullarımız və xidmətlərimiz haqqında da rəylərinizi alqışlayırıq, zəhmət olmasa sizə necə daha yaxşı xidmət göstərə biləcəyimizi bizimlə bölüşün!",
        "contact": "Əlaqə",
        "with_us": "Bizimlə",
        "related": "Əlaqəli",
        "no_review_yet": "Hələ məhsul nəzərdən keçirilməyib !!",
        "out_of_5": "5-dən",
        "from": "Etibarən",
        "same_shop": "eyni dükan",
        "tags": "Teqlər",
        "ships_from": "Gəmilər",
        "brand": "Marka",
        "description": "Təsvir",
        "specification": "Xüsusiyyətlər",
        "joined": "Qoşuldu",
        "response": "Cavab",
        "rate": "Dərəcəsi",
        "time": "Vaxt",
        "follower": "İzləyici",
        'products': "Məhsullar",
        'ratings': "Reytinqlər",
        'chat_now': "Теперь говорите",
        "follow": "İzləyin",
        "visit_shop": "Dükanı ziyarət edin",
        'home': "Ev",
        "about": "Haqqımızda Mystore",
        "how_to_earn": "Cashback qazanmaq üçün necə",
        "help": "Kömək edin",
        "contact_us": "Bizimlə əlaqə saxlayın",
        "faq": "Suallar",
        "mobile": "Mobil",
        "lang": "Azerbaijani",
        "currency": "AZN",
        "account": "Hesab",
        "dashboard": "İdarə paneli",
        "my_profile": "Mənim Hesabım",
        "my_orders": "Sifarişlərim",
        "my_wishlist": "Mənim İstəklərim",
        "header.my": "Başlıq",
        "messages": "Mesajlar",
        "notifications": "Bildirişlər",
        "logout": "Çıxış",
        "welcome": "Добро пожаловать в Mystore",
        "categories": "Kateqoriyalar",
        "searcha_product": "Bir məhsul axtarın",
        "empty_cart": "Sizin kartınız boşdur !",
        "ys_cart": "Səbətiniz",
        "subtotal": "Cəmi",
        "go_to_cart": "Səbətə gedin",
        "see_all": "Hamısını gör",
        "see_less": "Az baxın",
        "all": "Hamısı",
        "recommended_category": "Tövsiyə olunan kateqoriya",
        "flash": "Flaş",
        "deals": "əqdlər",
        "available": "Mövcuddur",
        'not_available': "Mövcud deyil",
        "sold": "Satıldı",
        "featured": "Seçilmiş",
        "latest": "Son",
        "discounts": "Endirimlər",
        "cashback": "Pulun qalığı",
        "comeback": "Geri qayıt",
        "load_more": "daha çox yüklə",
        "no_p_found": 'Məhsul tapılmadı',
        "featured_store": "Xüsusiyyət Mağazaları",
        "featured_mar": "Seçilmiş tacirlər",
        "official_mar": "Rəsmi tacirlər",
        "best_s_mar": "Ən çox satılan tacirlər",
        "top_rated_mar": "Ən çox qiymətləndirilən tacirlər",
        "feature": "Xüsusiyyət",
        "stores": "Mağaza",
        "no_s_found": "Mağaza tapılmadı",
        "items": "maddələr",
        "item": "Maddə",
        'pl_wish': "Zəhmət olmasa İstək siyahısına əlavə etmək üçün daxil olun",
        'close': "Yaxın",
        'Login': "Daxil ol",
        "sign_up": "Abunə olun",
        'sign_in': "Giriş",
        'sb_news': "Bülleten üçün abunə olun",
        "sb_news_desc": "Yeni məhsullarımız və xüsusi promosyonlarımız haqqında ani yenilikləri əldə edin!",
        'enter_email': "E-poçt ünvanınızı daxil edin",
        "how_to_buy": "Necə almaq olar?",
        "making_payment": "Ödənişlərin edilməsi",
        "delivery_options": "Çatdırılma Seçimləri",
        "buyer_protection": "Alıcının müdafiəsi",
        "new_user_guid": "Yeni istifadəçi təlimatı",
        "customer": "Müştəri",
        "service": "xidməti",
        "blog": "Blog",
        "terms_conditions": "Şərtlər və qaydalar",
        "privacy_policy": "Gizlilik Siyasəti",
        "partner_promotion": "Tərəfdaş Təqdimatı",
        "partnership": "Tərəfdaşlıq",
        "affiliate_p": "Tərəfdaşlıq Proqramı",
        "bro_cat": "Kateqoriya üzrə göz atın",
        "downld_oap": "Tətbiqimizi yükləyin",
        "all_rights_reserved": "Bütün hüquqlar qorunur.",
        "russian": "Rus",
        "usd": "ABŞ dolları",
        "azerbaijani": "Azərbaycan dili",
        "English": "İngilis dili",
        "azn": "Manat",
        "eur": "Avro",
        'category': "Kateqoriya",
        'shopping_product': "Alış-veriş məhsulları",
        'newest': "Ən yeni",
        'oldest': "Ən köhnə",
        'highest_price': "Ən yüksək qiymət",
        'lowest_price': "Ən aşağı qiymət",
        'ascending': "Artan",
        'descending': "Azalan",
        "pr_filter": "Фильтр продуктов",
        "price": "Qiymət",
        "range": "Menzil",
        'min': "MIN",
        'max': "MAX",
        "reviews": "Rəylər",
        "offers": "Təkliflər",
        'status': "Status",
        'stock': "Səhm",
        'off': "QAPALI",
        'color': "Rəng",
        'size': "Ölçü",
        "quantity": "Miqdarı",
        'add_to_cart': "Səbətə əlavə et",
        "share": "pay",
        "payment": "Ödəniş",
        "add_to_wishlist": "İstək siyahısına əlavə edin",
        'page_not_found': "Səhifə tapılmadı",
        'product_type': "Məhsulun növü",
        'product': "Məhsul",
        'info': "məlumat",
        'brand': "marka",
        'warranty': "zəmanət",
        'combine_shipping': "göndərmə birləşdirir",
        'shipping': "Göndərmə",
        'price': "qiymət",
        'to': "üçün",
        'shopping_cart': "Alış-veriş kartı",
        'select_all': "Hamısını seç",
        'delete': "Sil",
        'order_summary': "Sifariş Xülasə",
        'shipping_fee': "Göndərmə haqqı",
        'total': "Ümumi",
        'proceed_to_checkout': "Ödəməyə davam edin",
        'proceed_to_payment': "Ödənişə keçin",
        'order_now': "İndi sifariş et",
        'cart_items': "Səbət əşyaları",
        'shipping_info': "Göndərmə məlumatı",
        'completed': "Tamamlandı",
        'add_new_shipping_address': "Yeni Göndərmə Ünvanı əlavə edin",
        'edit_shipping_address': "Göndərmə Ünvanını redaktə edin",
        'oh_great': "Ah əla",
        'submit_successfully': "Uğurla göndərin",
        'shipping_zone': "Göndərmə zonası",
        'address': "Ünvan",
        'postal_code': "Poçt kodu",
        'floor': "Mərtəbə",
        'unit': "Vahid",
        'full_name': "Tam ad",
        'company_name': "Şirkət Adı",
        'optional': "İstəyə görə",
        'specific_instructions': "Xüsusi Təlimatlar",
        'cancel': "Ləğv et",
        'submit': "təqdim",
        'choose': "Seçin",
        'shipping_and_billing': "Göndərmə və Faturalandırma",
        'shipping_address': "Çatdırılma ünvanı",
        'billing_address': "Faktura ünvanı",
        'add_new': "Yeni əlavə edin",
        'edit': "Redaktə edin",
        'shipping_time': "Göndərmə vaxtı",
        'suspend_message': "Qaydaları və qaydaları pozduğunuz üçün müvəqqəti dayandırılırsınız!",
        'delete_message': "Mystore orqanı hesabınızı silin!",
        'for_more_info': "Daha çox məlumat üçün Mystore rəhbərliyinə müraciət edin.",
        'download_agreement': "Müqaviləni yükləyin",
        'agent_dashboard': "Agent Dashboard",
        'find_your_merchant': "Tacirinizi tapın",
        'product_category': "Məhsul Kateqoriyası",
        'send_request': "Sorğu göndərmək",
        'cancel_request': "İstəyi ləğv edin",
        'my_agents': "Mənim agentlərim",
        'my_agents_member_message': "Siz Mystore agentinin fəxri üzvüsünüz.",
        'get_agent_menu_message': "Agent menyusunu agent hesabına keçirmək üçün.",
        'become_an_agent_message': "Mystore agenti olmaq üçün Sazişi imzalamalı və Mystore ofisinə göndərməlisiniz.",
        'agent_profile': "Agent Profili",
        'profession': "Peşə",
        'social_links': "Sosial bağlantılar",
        'other_info': "Digər məlumatlar",
        'work_of_experience': "Təcrübə işi (illərlə)",
        'average_post_engaggement': "Orta Post Nişan",
        'purpose_to_be_an_agent': "Bir agent olmaq məqsədi",
        'update': "Yeniləyin",
        'or': "və ya",
        "add_new_zone":"Yeni Zona əlavə edin",
        "all_shipping_zones":"Bütün Göndərmə Bölgələri",
        "zone_details":"Zona Təfərrüatları",
        "pricing":"Qiymətləndirmə",
        "free_delivery":"Pulsuz çatdırılma",
        "shipping_day":"Göndərmə günü",
        "no_zone_found":"Zona tapılmadı!",
        "add_new_shop":"Yeni Mağaza əlavə edin",
        "shop_settings":"Mağaza parametrləri",
        "visit_shop":"Dükanı ziyarət edin",
        "manage_shop":"Mağazanı idarə edin",
        "comeback_history":"Geri qayıtma tarixi",
        "my_reviews":"Mənim Rəylərim",
        "product_name":"Məhsulun adı",
        "shop_name":"Mağaza Adı",
        "ratting":"Reytinq",
        "all_purchase_history":"Bütün alış tarixçəsi",
        "purchase_number":"Satınalma nömrəsi",
        "customer_name":"Müştəri adı",
        "phone_number":"Telefon nömrəsi",
        "purchase_warning":"Alış tarixçəsi tapılmadı!",

        "total_sale":"Ümumi Satış",
        "total_blogs":"Cəmi Bloglar",
        "successfull_orders":"Uğurlu Sifarişlər",
        "referral_requests":"İstək İstəkləri",
        "total_gave_comeback":"Toplam geri qayıtdı",
        "total_gave_cashback":"Total cashback verdi",
        "top_sale_products":"Ən çox satılan məhsullar",      
        "pending_orders":"Sifarişlər gözləyir",

        "download_agreement":"Müqaviləni yükləyin",
        "store_not_activated":"Mağazanız aktivləşdirilməyib",
        "sign_agreement":"Müqaviləni imzalamalı və mystore ofisinə göndərməlisiniz.",
        "trending_now":"İndi trend",
        "contact_us_at":"Hər hansı bir sualınız üçün bizə müraciət edin",
        "continue_shopping":"Alış-verişə davam edin",
        "customer_support:":"Müştəri dəstəyimiz",

        "email_to_us":"Bizə e-poçt göndərin - support@mystore.az Facebook səhifəmiz - mystore vasitəsilə əlaqə saxlayın",
        "terms_conditions":"Şərtlər və qaydalar",
        "privacy_policy":"Gizlilik Siyasəti",
        "new_user_guide":"Yeni istifadəçi təlimatı",
        "authors":"Müəlliflər",
        "posts_by":"Göndərənlər",
        "posts":"Mesajlar",
        "search_from":"Axtarış",
        "all_blogs_from ":"Bütün Bloglar",
        "by":"tərəfindən",

        "from":"Kimdən",
        "tags":"Teqlər",
        "related_articles":"Əlaqəli məqalələr",
        "more_from_author":"Müəllifdən daha çox",
        "comments":"Şərhlər",
        "previous_article":"Əvvəlki məqalə",
        "next_article":"Növbəti məqalə",
        "brand":"Marka",

        "shopping_products":"Alış-veriş məhsulları",
        "add_new_shipping_address":"Yeni Göndərmə Ünvanı əlavə edin",
        "wallet_credits":"Elektron cüzdan kreditləri",
        "available_credits":"Mövcud kreditlər",
        "use_partial_credits":"Qismən E-Cüzdan Kreditlərindən istifadə edin",
        "use_credits":"Kreditlərdən istifadə edin",

        "max_credits_use:":"Maks. istifadə edilə bilən kreditlər",
        "apply":"Müraciət edin",
        "credit_card":" Credit Card",
        "otp_message":"Doğrulama üçün Birdəfəlik Şifrənizi (OTP) daxil etmək üçün 3D Secure ™ ödəməsinə yönəldiləcəksiniz.",
        "confirm_otp":"OTP'yi təsdiqləyin",
    

    },
    en: {
        "reset_password": "Reset Password",
        'sending': "sending",
        'send_reset_p_link': "Send Password Reset Link ",
        "about":"About us Mystore",
        "how_to_earn":"How to Earn Cashback",
        "help":"Help",
        "contact_us":"Contact Us",
        "faq":"FAQ's",
        "mobile":"Mobile",
        "lang":"English",
        "currency":"USD",
        "account":"Account",
        "dashboard":"Dashboard",
        "my_profile":"My Profile",
        "my_orders":"My Orders",
        "my_wishlist":"My Wishlist",
        "header.my":"Header.My",
        "messages":"Messages",
        "notifications":"Notifications",
        "logout":"Log Out",
        "welcome":"Welcome to Mystore",
        "categories":"Categories",
        "searcha_product":"Search A Product",
        "empty_cart":"Your Cart Is Empty !",
        "ys_cart":"Your Shopping Cart",
        "subtotal":"Subtotal",
        "go_to_cart":"Go To Cart",
        "see_all":"See All", 
        "see_less":"See Less", 
        "all":"All",
        "recommended_category":"Recommended Category",
        "flash":"Flash",
        "deals":"Deals",
        "available":"Available",
        'not_available':"Not Available",
        "sold":"Sold",
        "featured":"Featured",
        "latest":"Latest",
        "discounts":"Discounts",
        "cashback":"Cashback",
        "comeback":"Comeback",
        "load_more":"Load More",
        "no_p_found":"No Products Found",
        "featured_store":"Feature Stores",
        "featured_mar":"Featured Merchants",
        "official_mar":"Official Merchants",
        "best_s_mar":"Best Selling Merchants",
        "top_rated_mar":"Top Rated Merchants",
        "feature":"Feature",
        "stores":"Stores",
        "no_s_found":"No Shop Found",
        "items":"Items",
        "item": "Item",
        'pl_wish':"Please Login For Add to Wishlist",
        'close':"Close",
        'Login':"Login",
        "sign_up":"Sign Up",
        'sign_in':"Sign In",
        'sb_news':"Subscribe For Newsletter",
        "sb_news_desc":"Get instant updates about our new products and special promos!",
        'enter_email':"Enter email address",
        "how_to_buy":"How to Buy",
        "making_payment":"Making Payments",
        "delivery_options": "Delivery Options",
        "delivery": "Delivery",
        "options":"Options",
        "buyer_protection":"Buyer Protection",
        "new_user_guid":"New User Guide",
        "customer":"Customer",
        "service":"Service",
        "blog":"Blog",
        "terms_conditions":"Terms & Conditions",
        "privacy_policy": "Privacy Policy",
        "privacy": "Privacy",
        "policy":" Policy",
        "and":"And",
        "partner_promotion":"Partner Promotion",
        "partnership":"Partnership",
        "affiliate_p":"Affiliate Program",
        "bro_cat":"Browse by Category",
        "downld_oap":"Download Our App",
        "all_rights_reserved":"All rights reserved.",
        "mystore":"Mystore",
        "russian":"Russian",
        "usd":"USD",
        "azerbaijani":"Azerbaijani",
        "English":"English",
        "azn":"AZN",
        "eur":"EUR",
        'category':"Category",
        'shopping_product':"Shopping Products",
        'newest':"Newest",
        'oldest':"Oldest",
        'highest_price':"Highest Price",
        'lowest_price':"Lowest Price",
        'ascending':"Ascending",
        'descending':"Descending",
        "pr_filter":"Product Filter",
        "price":"Price",
        "range":"Range",
        'min':"MIN",
        'max':"MAX",
        "reviews":"Reviews",
        "offers":"Offers",
        'home':"Home",
        'status':"Status",
        'stock':"Stock",
        'off':"OFF",
        'color':"Color",
        'size':"Size",
        "quantity":"Quantity",
        'add_to_cart':"Add to cart",
        "share":"Share",
        "payment": "Payment",
        "method": "Method",
        "visit_shop":"Visit Shop",
        "follow":"Follow",
        'chat_now':"Chat Now",
        'ratings':"Ratings",
        'products':"Products",
        "follower":"Follower",
        "response":"Response",
        "rate":"Rate",
        "time":"Time",
        "joined":"Joined",
        "specification":"Specification",
        "description":"Description",
        "brand":"Brand",
        "ships_from":"Ships From",
        "tags":"Tags",
        "from":"From the",
        "same_shop":"Same Shop",
        "out_of_5":"Out of 5",
        "no_review_yet":"There is no product review yet!!",
        "related":"Related",
        "contact":"Contact",
        "with_us":"With Us",
        "contact_description":"Have a question or an issue with your account? No worries, just let us know, and we'll get back to you, anytime of the day! We welcome feedback on our products and services as well, please share with us how we can better serve you!",
        "your_name":"Your Name*",
        "your_email":"Your Email*",
        "your_phone":"Your Phone*",
        "select_subject":"Select Subject",
        "general_enquiry":"General Enquiry",
        "feedback_ois":"Feedback on Issues/Bugs",
        "adver_enq":"Advertising Enquiry",
        "send_msg":"Send Message",
        "your_msg":"Your Message",
        "flash_deal_products":"Flash Deal Products",
        "nFlashpf":"No flashdeal product found",
        "chat":"Chat",
        "following":"Following",
        "shopping":"Shopping",
        'store_information':"Store Information",
        "operating_hours":"Operating Hours",
        "open":"Open",
        "closed":"Closed",
        "exp_holidays":"Except public holidays",
        'submitreview':"Submit a Review",
        "review_message":"Only registered users can write reviews",
        "store_location":"Store Location",
        "language":"Language",
        "currenci":"Currency",
        'login_header':"Login Header",
        'email':'Email',
        'password':'Password',
        'remember_me':"Remember Me",
        'forgot_passowrd':'Forget Password',
        'checking':"Checking",
        'or_login_with':"or log in with",
        'need_an_account':"Need An Account",
        'register_now':'Register Now',
        'buy_sell_mystore_desc':'Buy and Sell Easy Only at Mystore',
        'login_feel_mystore_desc':'Login and feel the ease of doing transactions on Mystore',
        'go_to_homepage':"Go to Homepage",
        "unfollow":"Unfollow",
        "recently_rev_notfications":"Recently Received Notifications",
        "add_to_wishlist":"Add to wishlist",
        'price_icon':"$",
        'maximum_price':"Maximum Price",
        'minimum_price':"Minimum price",
        'page_not_found':"Page Not Found",
        'shippings':"Shippings",
        'filter':"Filter",
        'category_name':'Category Name',
        'sizes':"Sizes",
        'colors': "Colors",
        'types':'Types',
        'brands':"Brands",
        "affiliate":"Affiliate",
        "program":"Program",
        "buyer": "Buyer",
        "_protection":"Protection",
        "_faqs":"FAQs",
        'create_account':'Create An Account',
        'already_account':'Already have an account',
        'name':"Name",
        'phone_number':'Phone Number',
        'confirm_password':" Confirm Password",
        'bterm_conditions':"By signing up you agree to our Terms & Conditions",
        'or_sign_up_with':"or sign up with",
        'product_type':"Product Type",
        'product': "Product",
        'info': "info",
        'brand': "brand",
        'warranty': "warranty",
        'combine_shipping': "combine shipping",
        'shipping': "shipping",
        'price': "price",
        'to': "to",
        'shopping_cart': "Shopping Cart",
        'select_all': "Select All",
        'delete': "Delete",
        'order_summary': "Order Summary",
        'shipping_fee': "Shipping Fee",
        'total': "Total",
        'proceed_to_checkout': "Proceed to Checkout",
        'proceed_to_payment': "Proceed to Payment",
        'order_now': "Order Now",
        'cart_items': "Cart Items",
        'shipping_info': "Shipping Info",
        'completed': "Completed",
        'add_new_shipping_address': "Add New Shipping Address",
        'edit_shipping_address': "Edit Shipping Address",
        'oh_great': "Oh Great",
        'submit_successfully': "Submit Successfully",
        'shipping_zone': "Shipping Zone",
        'address': "Address",
        'postal_code': "Postal Code",
        'floor': "Floor",
        'unit': "Unit",
        'full_name': "Full Name",
        'company_name': "Company Name",
        'optional': "Optional",
        'specific_instructions': "Specific Instructions",
        'cancel': "Cancel",
        'submit': "Submit",
        'choose': "Choose",
        'shipping_and_billing': "Shipping & Billing",
        'shipping_address': "Shipping Address",
        'billing_address': "Billing Address",
        'add_new': "Add New",
        'edit': "Edit",
        'shipping_time': "Shipping Time",
        'suspend_message': "You are suspended for breaking rules and regulations!",
        'delete_message': "Mystore authority delete your account!",
        'for_more_info': "For more information contact to Mystore authority.",
        'download_agreement': "Download Agreement",
        'agent_dashboard': "Agent Dashboard",
        'find_your_merchant': "Find your merchant",
        'product_category': "Product Category",
        'send_request': "Send Request",
        'cancel_request': "Cancel Request",
        'my_agents': "My Agents",
        'my_agents_member_message': "You are an Honorable Member of Mystore agent.",
        'get_agent_menu_message': "To get the agent menu switch to the agent account.",
        'become_an_agent_message': "To become a Mystore agent, you need to sign the  Agreement and send it to Mystore office.",
        'agent_profile': "Agent Profile",
        'profession': "Profession",
        'social_links': "Social Links",
        'other_info': "Other Info",
        'work_of_experience': "Work of Experience (in years)",
        'average_post_engaggement': "Average Post Engagement",
        'purpose_to_be_an_agent': "Purpose to be an agent",
        'update': "Update",
        'or': "or",
        "add_new_zone":"Add New Zone",
        "all_shipping_zones":"All Shipping Zones",
        "zone_details":"Zone Details",
        "pricing":"Pricing",
        "free_delivery":"Free Delivery",
        "shipping_day":"Shipping Day",
        "no_zone_found":"No Zone Found!",
        "add_new_shop":"Add New Shop",
        "shop_settings":"Shop Settings",
        "visit_shop":"Visit Shop",
        "manage_shop":"Manage Shop",
        "comeback_history":"Comeback History",
        "my_reviews":"My Reviews",
        "product_name":"Product Name",
        "shop_name":"Shop Name ",
        "ratting":"Ratting",
        "all_purchase_history":"All Purchase History",
        "purchase_number":"Purchase Number",
        "customer_name":"Customer Name",
        "phone_number":"Phone Number",
        "purchase_warning":"No Purchase History Found!",

        "total_sale":"Total Sale",
        "total_blogs":"Total Blogs",
        "successfull_orders":"Successfull Orders",
        "referral_requests":"Referral Requests",
        "total_gave_comeback":"Total Gave Comeback",
        "total_gave_cashback":"Total Gave Cashback",
        "top_sale_products":"Top Sale Products",      
        "pending_orders":"Pending orders", 

        "download_agreement":"Download Agreement",
        "store_not_activated":"Your store is not activated!",
        "sign_agreement":"you  need to sign the  Agreement  and send to mystore office.",
        "trending_now":"Trending Now",
        "contact_us_at":"For any enquiries, please contact us at",
        "continue_shopping":"Continue Shopping",
        "customer_support:":"Our Customer Support:",

        "email_to_us":"Email to us - support@mystore.az Contact us via our Facebook Page - mystore",
        "terms_conditions":"Terms & Conditions",
        "privacy_policy":"Privacy Policy",
        "new_user_guide":"New User Guide",
        "authors":"Authors",
        "posts_by":"Posts by",
        "posts":"Posts",
        "search_from":"Search From",
        "all_blogs_from ":"All Blogs From ",
        "by":"By",

        "from":"From",
        "tags":"Tags",
        "related_articles":" Related Articles",
        "more_from_author":"More From Author",
        "comments":"Comments",
        "previous_article":" Previous article",
        "next_article":"Next article",
        "brand":"Brand",

        "shopping_products":"Shopping Products",
        "add_new_shipping_address":"Add New Shipping Address",
        "wallet_credits":"E-Wallet Credits",
        "available_credits":"Available Credits",
        "use_partial_credits":"Use Partial E-Wallet Credits",
        "use_credits":"Use credits",

        "max_credits_use:":" Max. credits that can be use:",
        "apply":"Apply",
        "credit_card":"Credit Card",
        "otp_message":"You will be directed to a 3D Secure™ payment to key in your One-Time Password (OTP) for verification.",
        "confirm_otp":" CONFIRM OTP",
       
    },
    ru: {
        "reset_password":"Сброс пароля",
        'sending': "отправка",
        'send_reset_p_link':"Отправить ссылку для сброса пароля",
        'ascending':"Восходящий",
        'name': "название",
        'phone_number': 'Телефонный номер',
        'confirm_password': "Подтвердить Пароль",
        'bterm_conditions': "Регистрируясь, вы соглашаетесь с нашими Условиями использования.",
        'or_sign_up_with': "или зарегистрируйтесь с",
        'already_account': 'Уже есть аккаунт',
        'create_account': 'Завести аккаунт',
        "conditions": 'Условия',
        "term": "срок",
        "privacy": "Конфиденциальность",
        "policy": "Политика",
        "and": "А также",
        "method": "Метод",
        "_faqs": "Часто задаваемые вопросы",
        "delivery": "Доставка",
        "options": "Параметры",
        "buyer": "Покупатель",
        "_protection": "Защита",
        "affiliate": "Партнер",
        "program": "Программа",
        'brands': "Бренды",
        'types': 'типы',
        'colors': "Цвета",
        'sizes': "Размеры",
        'category_name': 'Название категории',
        'filter': 'фильтр',
        'shippings': "Доставка",
        'minimum_price': "Минимальная цена",
        'maximum_price': "Максимальная цена",
        'price_icon': "€",
        "recently_rev_notfications": "Недавно полученные уведомления",
        "unfollow": "Отписаться",
        'go_to_homepage':"Вернуться на домашнюю страницу",
        'login_feel_mystore_desc':'Войдите в систему и почувствуйте легкость совершения транзакций в Mystore',
        'buy_sell_mystore_desc':'Легко покупать и продавать только в Mystore',
        'register_now':'Зарегистрируйтесь сейчас',
        'need_an_account':"Нужен аккаунт",
        'or_login_with':"или войдите с помощью",
        'checking':"Проверка",
        'forgot_passowrd':'Забыли пароль',
        'remember_me':"Запомнить меня",
        'password':'пароль',
        'email':'Эл. адрес',
        'login_header':"Заголовок входа",
        "currenci":"валюта",
        "language":"Язык",
        "store_location":"Расположение магазина",
        "review_message":"Только зарегистрированные пользователи могут оставлять отзывы",
        'submitreview':"Отправить отзыв",
        "open":"открыто",
        "closed":"Закрыто",
        "exp_holidays":"Кроме государственных праздников",
        "operating_hours":"Часы работы",
        'store_information':"Информация о магазине",
        "shopping":"Покупка",
        "following":"Следующий",
        "chat":"Чат",
        "nFlashpf":"Не найдено мгновенных предложений",
        "flash_deal_products":"Горящие предложения",
        "your_msg":"Твое сообщение",
        "select_subject":"Выберите тему",
        "general_enquiry":"Общий запрос",
        "feedback_ois":"Отзыв о проблемах / ошибках",
        "adver_enq":"Запрос на рекламу",
        "send_msg":"Отправить сообщение",
        "your_name":"Ваше имя*",
        "your_email":"Ваш адрес электронной почты*",
        "your_phone":"Ваш телефон*",
        "contact_description":"У вас есть вопрос или проблема с вашей учетной записью? Не беспокойтесь, просто дайте нам знать, и мы свяжемся с вами в любое время дня! Мы также приветствуем отзывы о наших продуктах и услугах. Пожалуйста, поделитесь с нами, как мы можем лучше обслуживать вас!",
        "contact":"Связаться",
        "with_us":"С нами",
        "related":"связанные с",
        "no_review_yet":"Еще нет обзора продукта !!",
        "out_of_5":"Из 5",
        "from":"Из",
        "same_shop":"Тот же магазин",
        "tags":"Теги",
        "ships_from":"Доставка из",
        "brand":"Марка",
        "description":"Описание",
        "specification":"Спецификация",
        "joined":"Присоединился",
        "response":"отклик",
        "rate":"Темп",
        "time":"Время",
        "follower":"Последователь",
        'products':"Продукты",
        "chat_now":"İndi söhbət edin",
        "about": "около",
        "how_to_earn":"Как заработать кэшбэк",
        "help":"Помогите",
        "contact_us":"Связаться с нами",
        "faq":"FAQ's",
        "mobile":"мобильный",
        "lang":"Russian",
        "currency":"EUR",
        "account":"Счет",
        "dashboard":"Панель приборов",
        "my_profile":"Мой профиль",
        "my_orders":"мои заказы",
        "my_wishlist":"мой список желаний",
        "header.my":"Заголовок.Мой",
        "messages":"Сообщения",
        "notifications":"Уведомления",
        "logout":"Выйти",
        "welcome":"Mystore-a xoş gəlmisiniz",
        "categories":"категории",
        "searcha_product":"Искать продукт",
        "empty_cart":"Ваша корзина пуста !",
        "ys_cart":"Ваша Корзина",
        "subtotal":"Промежуточный итог",
        "go_to_cart":"В корзину",
        "see_all":"Увидеть все", 
        "see_less":"Видеть меньше", 
        "all":"все",
        "recommended_category":"Рекомендуемая категория",
        "flash":"Горящие",
        "deals":"предложения",
        "available":"Доступный",
        'not_available':"недоступно",
        "sold":"Продан",
        "featured":"Рекомендуемые",
        "latest":"Последний",
        "discounts":"Скидки",
        "cashback":"Возврат наличных",
        "comeback":"Возвращения",
        "load_more":"Загрузи больше",
        "no_p_found":"Товаров не найдено",
        "featured_store":"Функциональные магазины",
        "featured_mar":"любимые торговцы",
        "official_mar":"Официальные торговцы",
        "best_s_mar":"Самые продаваемые продавцы",
        "top_rated_mar":"Лучшие продавцы",
        "feature":"Особенность",
        "stores":"магазины",
        "no_s_found":"Магазин не найден",
        "items":"Предметы",
        "item": "Пункт",
        'pl_wish':"Пожалуйста, войдите, чтобы добавить в список желаний",
        'close':"Закрыть",
        'Login':"Авторизоваться",
        "sign_up":"Подписаться",
        'sign_in':"Войти в систему",
        'sb_news':"Подпишитесь на рассылку новостей",
        "sb_news_desc":"Получайте мгновенные обновления о наших новых продуктах и специальных акциях!",
        'enter_email':"Введите адрес электронной почты",
        "how_to_buy":"Как купить",
        "making_payment":"Совершение платежей",
        "delivery_options":"Варианты доставки",
        "buyer_protection":"Защита Покупателя",
        "new_user_guid":"Новое руководство пользователя",
        "customer":"Обслуживание",
        "service":"клиентов",
        "blog":"Блог",
        "terms_conditions":"Условия и положения",
        "privacy_policy":"политика конфиденциальности",
        "partner_promotion":"Партнерское продвижение",
        "partnership":"партнерство",
        "affiliate_p":"Партнерская программа",
        "bro_cat":"Просмотр по категориям",
        "downld_oap":"Загрузите наше приложение",
        "all_rights_reserved":"Все права защищены.",
        "mystore":"Mystore",
        "russian":"русский",
        "usd":"доллар США",
        "azerbaijani":"Азербайджанский",
        "English":"английский",
        "azn":"Манат",
        "eur":"евро",
        'category':"Категория",
        'shopping_product':"Товары для покупок",
        'newest':"Новейшие",
        'oldest':"Самый старый",
        'highest_price':"Самая высокая цена",
        'lowest_price':"Самая низкая цена",
        'asending':"по возрастанию",
        'descending':"По убыванию",
        "pr_filter":"Фильтр продуктов",
        "price":"Цена",
        "range":"Диапазон",
        'min':"MIN",
        'max':"MAX",
        "reviews":"Отзывы",
        "offers":"Предложения",
        'home':"Главная",
        'status':"Статус",
        'stock':"Склад",
        'off':"ВЫКЛ.",
        'color':"цвет",
        'size':"Размер",
        "quantity":"Количество",
        'add_to_cart':"Добавить в корзину",
        "share":"Поделиться",
        "payment":"Оплата",
        "visit_shop":"Посетить магазин",
        "follow":"следить",
        'ratings':"Рейтинги",
        "add_to_wishlist":"Добавить в список желаний",
        'page_not_found':"Страница не найдена",
        'product_type':"Тип продукта",
        'product': "Товар",
        'info': "Информация",
        'brand': "марка",
        'warranty': "гарантия",
        'combine_shipping': "объединить доставку",
        'shipping': "Перевозка",
        'price': "цена",
        'to': "к",
        'shopping_cart': "Корзина покупателя",
        'select_all': "Выбрать все",
        'delete': "удалять",
        'order_summary': "итог заказа",
        'shipping_fee': "Стоимость доставки",
        'total': "Общее",
        'proceed_to_checkout': "Пройти к кассе",
        'proceed_to_payment': "Перейти к оплате",
        'order_now': "Заказать сейчас",
        'cart_items': "Товары в корзине",
        'shipping_info': "Информация о доставке",
        'completed': "Завершено",
        'add_new_shipping_address': "Добавить новый адрес доставки",
        'edit_shipping_address': "Изменить адрес доставки",
        'oh_great': "О, круто",
        'submit_successfully': "Отправить успешно",
        'shipping_zone': "Зона доставки",
        'address': "Адрес",
        'postal_code': "Почтовый Код",
        'floor': "Пол",
        'unit': "Ед. изм",
        'full_name': "ФИО",
        'company_name': "Название компании",
        'optional': "По желанию",
        'specific_instructions': "Особые инструкции",
        'cancel': "Отмена",
        'submit': "представить",
        'choose': "выбирать",
        'shipping_and_billing': "Доставка и выставление счетов",
        'shipping_address': "Адрес доставки",
        'billing_address': "Платежный адрес",
        'add_new': "Добавить новое",
        'edit': "редактировать",
        'shipping_time': "Время доставки",
        'suspend_message': "Вас дисквалифицировали за нарушение правил и норм!",
        'delete_message': "Авторитет Mystore удалите вашу учетную запись!",
        'for_more_info': "Для получения дополнительной информации свяжитесь с администрацией Mystore.",
        'download_agreement': "Скачать Соглашение",
        'agent_dashboard': "Панель управления агента",
        'find_your_merchant': "Найдите своего продавца",
        'product_category': "категория продукта",
        'send_request': "Послать запрос",
        'cancel_request': "Отменить запрос",
        'my_agents': "Мои агенты",
        'my_agents_member_message': "Вы являетесь Почетным членом агента Mystore.",
        'get_agent_menu_message': "Чтобы получить меню агента, перейдите в учетную запись агента.",
        'become_an_agent_message': "Чтобы стать агентом Mystore, вам необходимо подписать Соглашение и отправить его в офис Mystore.",
        'agent_profile': "Профиль агента",
        'profession': "Профессия",
        'social_links': "Социальные ссылки",
        'other_info': "Дополнительная информация",
        'work_of_experience': "Опыт работы (в годах)",
        'average_post_engaggement': "Среднее взаимодействие с публикацией",
        'purpose_to_be_an_agent': "Цель быть агентом",
        'update': "Обновить",
        'or': "или же",
        "add_new_zone":"Добавить новую зону",
        "all_shipping_zones":"Все зоны доставки",
        "zone_details":"Детали зоны",
        "pricing":"Ценообразование",
        "free_delivery":"Бесплатная доставка",
        "shipping_day":"День доставки",
        "no_zone_found":"Зона не найдена!",
        "add_new_shop":"Добавить новый магазин",
        "shop_settings":"Настройки магазина",
        "visit_shop":"Посетить магазин",
        "manage_shop":"Управление магазином",
        "comeback_history":"История возвращения",
        "my_reviews":"Мои обзоры",
        "product_name":"наименование товара",
        "shop_name":"Название магазина ",
        "ratting":"Рейтинг",
        "all_purchase_history":"Вся история покупок",
        "purchase_number":"Номер покупки",
        "customer_name":"Имя Клиента",
        "phone_number":"Телефонный номер",
        "purchase_warning":"История покупок не найдена!",
        "total_sale":"Общая продажа",
        "total_blogs":"Всего блогов",
        "successfull_orders":"Успешные заказы",
        "referral_requests":"Реферальные запросы",
        "total_gave_comeback":"Всего отдал кэшбэк",
        "total_gave_cashback":"Всего Отдал Вернись",
        "top_sale_products":"Лучшие товары для продажи",      
        "pending_orders":"Заказы в ожидании",
        "download_agreement":"Скачать Соглашение",
        "store_not_activated":"Ваш магазин не активирован",
        "sign_agreement":"Вам необходимо подписать договор и отправить в офис mystore.",
        "trending_now":"Актуальные",
        "contact_us_at":"По любым вопросам обращайтесь к нам по адресу",
        "continue_shopping":"Продолжить покупки",
        "customer_support:":"Наша служба поддержки",
        "email_to_us":"Напишите нам - support@mystore.az Свяжитесь с нами через нашу страницу в Facebook - mystore",
        "terms_conditions":"Условия и положения",
        "privacy_policy":"политика конфиденциальности",
        "new_user_guide":"Новое руководство пользователя",
        "authors":"Авторы",
        "posts_by":"Сообщения от",
        "posts":"Сообщения",
        "search_from":"Искать из",
        "all_blogs_from ":"Все блоги от",
        "by":"По",
        "from":"Из",
        "tags":"Теги",
        "related_articles":"Статьи по Теме",
        "more_from_author":"Ещё от автора",
        "comments":"Комментарии",
        "previous_article":"Предыдущая статья",
        "next_article":"Следующая статья",
        "brand":"Марка",

        "shopping_products":"Товары для покупок",
        "add_new_shipping_address":"Добавить новый адрес доставки",
        "wallet_credits":"Кредиты на электронный кошелек",
        "available_credits":"Доступные кредиты",
        "use_partial_credits":"Использовать частичные кредиты электронного кошелька",
        "use_credits":"Использовать кредиты",

        "max_credits_use:":"Максимум. кредиты, которые можно использовать",
        "apply":"Применять",
        "credit_card":"Кредитная карта",
        "otp_message":"Вы будете перенаправлены на платеж 3D Secure ™, чтобы ввести одноразовый пароль (OTP) для проверки.",
        "confirm_otp":"ПОДТВЕРДИТЬ OTP",
    }
}